use multiple keyservers

diff --git a/jdk8/Dockerfile b/jdk8/Dockerfile
--- a/jdk8/Dockerfile
+++ b/jdk8/Dockerfile
@@ -9,11 +9,31 @@ RUN set -o errexit -o nounset \
 	&& echo "Downloading Groovy" \
 	&& wget --no-verbose --output-document=groovy.zip "https://dist.apache.org/repos/dist/release/groovy/${GROOVY_VERSION}/distribution/apache-groovy-binary-${GROOVY_VERSION}.zip" \
 	\
+	&& echo "Importing keys listed in http://www.apache.org/dist/groovy/KEYS from key server" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& for key in \
+		"0x41321490758AAD6F" \
+		"0x825C06C827AF6B66" \
+		"0x6A65176A0FB1CD0B" \
+	; do \
+		for server in \
+			ha.pool.sks-keyservers.net \
+			hkp://p80.pool.sks-keyservers.net:80 \
+			pgp.mit.edu \
+		; do \
+			echo "  Trying ${server}"; \
+			if gpg --keyserver "${server}" --recv-keys "${key}"; then \
+				break; \
+			fi; \
+		done; \
+	done; \
+	if [ $(gpg --list-keys | grep -c "pub ") -ne 3 ]; then \
+		echo "ERROR: Failed to fetch GPG keys" >&2; \
+		exit 1; \
+	fi \
+	\
 	&& echo "Checking download signature" \
 	&& wget --no-verbose --output-document=groovy.zip.asc "https://dist.apache.org/repos/dist/release/groovy/${GROOVY_VERSION}/distribution/apache-groovy-binary-${GROOVY_VERSION}.zip.asc" \
-	&& export GNUPGHOME="$(mktemp -d)" \
-	&& echo "Importing keys listed in http://www.apache.org/dist/groovy/KEYS from key server" \
-	&& gpg --keyserver pgp.mit.edu --recv-keys "0x41321490758AAD6F" "0x825C06C827AF6B66" "0x6A65176A0FB1CD0B" \
 	&& gpg --batch --verify groovy.zip.asc groovy.zip \
 	&& rm --recursive "${GNUPGHOME}" \
 	&& rm groovy.zip.asc \
@@ -21,7 +41,7 @@ RUN set -o errexit -o nounset \
 	&& echo "Installing Groovy" \
 	&& unzip groovy.zip \
 	&& rm groovy.zip \
-	&& mv "groovy-${GROOVY_VERSION}" "${GROOVY_HOME}" \
+	&& mv "groovy-${GROOVY_VERSION}" "${GROOVY_HOME}/" \
 	&& ln --symbolic "${GROOVY_HOME}/bin/grape" /usr/bin/grape \
 	&& ln --symbolic "${GROOVY_HOME}/bin/groovy" /usr/bin/groovy \
 	&& ln --symbolic "${GROOVY_HOME}/bin/groovyc" /usr/bin/groovyc \
@@ -36,8 +56,11 @@ RUN set -o errexit -o nounset \
 	&& mkdir --parents /home/groovy/.groovy/grapes \
 	&& chown --recursive groovy:groovy /home/groovy
 
+# Create Grapes volume
 USER groovy
 VOLUME "/home/groovy/.groovy/grapes"
 WORKDIR /home/groovy
 
-RUN groovy --version
+RUN set -o errexit -o nounset \
+	&& echo "Testing Groovy installation" \
+	&& groovy --version
